In [1]:
import numpy as np

In [18]:
n_states = 5 # 0 to 4
goal_state = 4
actions = [0, 1] # 0 = move left, 1 = move right

Q = np.zeros((n_states, len(actions)))

In [3]:
Q

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

So this is essentially an adjacency matrix from states to actions: rows being states 0 to 4 (e.g. position along x-axis) and columns being actions 0 or 1 to take in that state. 

Here the goal state is the last (4, right on x-axis, say). So we want in states 0 through 3 to take the action 1 (move right) to reach state 4. Do we then stop, or is there a 'goal reached' state?

The correct Q matrix we want to learn is thus (I think):
```python
array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.]])
```


In [10]:
T = np.arange(10).reshape((5,2))
T

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
state = 2
T[state]

array([4, 5])

So, given Q, we can get the action (of our current policy) for a given state by going `np.argmax(Q[state])`. 

In the above example with T=Q, that'd give us 1, because 5 is the highest and its index is 1 (argmax).

In [30]:
for episode in range(5):
    state = 0
    
    action = np.argmax(Q[state])
    
    if action == 0:
        # move left
        next_state = max(0, state-1) # unless state already zero, decrement state by one
    else:
        # move right
        next_state = min(n_states-1, state+1) # unless state already 4 (n_states-1), increment state by one
    print(next_state)

0
0
0
0
0


In [31]:
for episode in range(5):
    state = 0
    
    action = np.argmax(Q[state])
    
    if action == 0:
        # move left
        next_state = max(0, state-1) # unless state already zero, decrement state by one
    else:
        # move right
        next_state = min(n_states-1, state+1) # unless state already 4 (n_states-1), increment state by one
    
    reward = 1 if next_state == goal_state else 0
    print(Q)
    
    Q[state, action] += reward + np.max(Q[next_state]) - Q[state, action]
    state = next_state

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


This way nothing would ever happen to change the policy, even if we added learning rates or discount factors.

What we need is *exploration*: randomly, on some episodes, choose an action *randomly*.

In [68]:
np.random.rand() # generates random number between 0 and 1 uniformly

0.1190781417681448

In [77]:
EXPLORATION_RATE = 0.1 # less than 10% chance of getting number less than 0.1 from [0,1]

for episode in range(100): # on 100 episodes ~10 will explore and ~90 will use policy
    state = 0
    
    if np.random.rand() < EXPLORATION_RATE:
        # take RANDOM action
        action = np.random.choice(actions)
        print('EXPLORED:', action)
    else: 
        # take action from policy
        action = np.argmax(Q[state])
    
    if action == 0:
        # move left
        next_state = max(0, state-1) # unless state already zero, decrement state by one
    else:
        # move right
        next_state = min(n_states-1, state+1) # unless state already 4 (n_states-1), increment state by one
    print(state, '-->', next_state)
    reward = 1 if next_state == goal_state else 0
    print(Q)
    
    Q[state, action] += reward + np.max(Q[next_state]) - Q[state, action]
    state = next_state

0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
EXPLORED: 1
0 --> 1
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]

In [78]:
EXPLORATION_RATE = 0.1 # less than 10% chance of getting number less than 0.1 from [0,1]

for episode in range(100): # on 100 episodes ~10 will explore and ~90 will use policy
    state = 0
    
    if np.random.rand() < EXPLORATION_RATE:
        # take RANDOM action
        action = np.random.choice(actions)
        print('EXPLORED:', action)
    else: 
        # take action from policy
        action = np.argmax(Q[state])
    
    if action == 0:
        # move left
        next_state = max(0, state-1) # unless state already zero, decrement state by one
    else:
        # move right
        next_state = min(n_states-1, state+1) # unless state already 4 (n_states-1), increment state by one
    print(state, '-->', next_state)
    reward = 1 if next_state == goal_state else -0.01
    print(Q)
    
    Q[state, action] += reward + np.max(Q[next_state]) - Q[state, action]
    state = next_state

0 --> 0
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0 --> 1
[[-0.01  0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
0 --> 0
[[-0.01 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
0 --> 1
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
0 --> 1
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
0 --> 1
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
0 --> 1
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
0 --> 1
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
0 --> 1
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
EXPLORED: 0
0 --> 0
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
EXPLORED: 1
0 --> 1
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]]
0 --> 1
[[-0.02 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]

In [83]:
n_states = 2 # 0 to 4
goal_state = 1
actions = [0, 1] # 0 = move left, 1 = move right

Q = np.zeros((n_states, len(actions)))

EXPLORATION_RATE = 0.1 # less than 10% chance of getting number less than 0.1 from [0,1]

for episode in range(10): # on 100 episodes ~10 will explore and ~90 will use policy
    state = 0
    
    if np.random.rand() < EXPLORATION_RATE:
        # take RANDOM action
        action = np.random.choice(actions)
        print('EXPLORED:', action)
    else: 
        # take action from policy
        action = np.argmax(Q[state])
    
    if action == 0:
        # move left
        next_state = max(0, state-1) # unless state already zero, decrement state by one
    else:
        # move right
        next_state = min(n_states-1, state+1) # unless state already 4 (n_states-1), increment state by one
    print(state, '-->', next_state)
    reward = 1 if next_state == goal_state else 0
    print(Q)
    
    Q[state, action] += reward + np.max(Q[next_state]) - Q[state, action]
    state = next_state

EXPLORED: 0
0 --> 0
[[0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]]
0 --> 0
[[0. 0.]
 [0. 0.]]
EXPLORED: 1
0 --> 1
[[0. 0.]
 [0. 0.]]
0 --> 1
[[0. 1.]
 [0. 0.]]


In [85]:
np.argmax(Q[0])

1

So here we've at least learned to take the right action (1, move right) in a two-state system.

In [99]:
# Bandit probabilities (chance of giving reward)
bandit_probs = [0.7, 0.3]  # Two slot machines

# Initialize Q-values (estimated value of each action)
Q = np.zeros(2)

# Hyperparameters
num_episodes = 1000
epsilon = 0.1  # Exploration rate
alpha = 0.1    # Learning rate

# Training loop
for _ in range(num_episodes):
    # Epsilon-greedy action selection
    if np.random.random() < epsilon:
        action = np.random.randint(2)  # Explore
    else:
        action = np.argmax(Q)          # Exploit
    
    # Simulate reward (1 with probability, 0 otherwise)
    reward = 1 if np.random.random() < bandit_probs[action] else 0
    
    # Update Q-value using simple average
    Q[action] += alpha * (reward - Q[action])

print("Learned Q-values:", Q)
print("Optimal action:", np.argmax(Q))

Learned Q-values: [0.63477863 0.21979466]
Optimal action: 0
